name: WHITEEAR
description: WHITEEAR personal blogging system. life | programming 

#url: http://brianmaierjr.github.com/long-haul
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: 首页
   url: /index.html
 - title: 人生
   url: /life.html
 - title: 程序
   url: /programming.html
 - title: 关于
   url: /about.html
 - title: 联系
   url: /contact.html

###
# info
user:
  name: chunyang liu
  email: cyliu7@gmail.com
  twitter: \@cyliu7
  facebook: https://facebook.com/chunyang.liu.9
  weibo: \@代码厨子

###
# comments support
comments:
 enable: true
 engine: disqus

