markdown: rdiscount
#markdown: kramdown
#markdown: redcarpet2
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

permalink: /:year/:month/:title/
url: http://whiteear.github.io/
author: whiteear 
pygments: true
paginate: 24

ditu:
  section: <div style="width:100%; height:550px; border:#ccc solid 1px;" id="dituContent"></div>
