name: WHITEEAR
description: WHITEEAR personal blogging system. life | programming 

#url: http://brianmaierjr.github.com/long-haul
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html
 - title: Programming
   url: /programming.html

###
# info
user:
  name: chunyang liu
  email: cyliu7@gmail.com
  twitter: \@cyliu7
  facebook: https://facebook.com/chunyang.liu.9
  weibo: \@代码厨子

###
# comments support
comments:
 enable: true
 engine: disqus

